title: Karine Levonyan
first_name: Karine
last_name: Levonyan
email: ""
description: Research Scientist / AI
baseurl: ""
url: "https://karinelevonyan.github.io"
max_width: 800px
 

# Social / Scholar
scholar_userid: L--pFAcAAAAJ
github_username: KarineLevonyan

navbar_fixed: true
footer_fixed: true
search_enabled: false
blog_name: blog
permalink: /blog/:year/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project