title: Karine Levonyan
first_name: Karine
last_name: Levonyan
email: ""
description: Research Scientist / AI
baseurl: ""
url: "https://karinelevonyan.github.io"


navbar_fixed: true
footer_fixed: true
search_enabled: false
blog_name: blog
permalink: /blog/:year/:title/

collections:
  news:
    defaults:
      layout: post
  pages:
    output: true
    permalink: /pages/:path/
  projects:
    output: true
    permalink: /projects/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: "_pages"
      type: pages        # ← this makes _pages/ files get processed
    values:
      layout: page
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project