title: Karine Levonyan
first_name: Karine
last_name: Levonyan
email: ""
description: Research Scientist / AI
baseurl: ""
url: "https://karinelevonyan.github.io"

max_width: 800px

# Social / Scholar
scholar_userid: L--pFAcAAAAJ
github_username: KarineLevonyan

navbar_fixed: true
footer_fixed: true
search_enabled: false
blog_name: blog
permalink: /blog/:year/:title/

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project

# Third party libraries
third_party_libraries:
  jquery:
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"
    integrity:
      js: "sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  mdb:
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js"
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"